### ISSUE TITLE
红绿灯数据集

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#11]
我算法要测试几种 测试指标方面有什么要求吗

**Comment by foww-0001** [comment]
数据格式样例：
https://github.com/MiniBullLab/easy_sample_mark/blob/master/docs/%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8%E6%A0%BC%E5%BC%8F.md

**Comment by foww-0001** [comment]
> 我算法要测试几种 测试指标方面有什么要求吗

acc1和acc5的结果
