### ISSUE TITLE
easy_ai运行问题

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#13]
在运行train_task.py时报错

<img width="870" alt="Screen Shot 2022-05-09 at 11 58 49" src="https://user-images.githubusercontent.com/77905715/167338281-9919bc20-8767-40af-b0cc-a72182fe767c.png">

**Comment by foww-0001** [comment]
把运行命令贴上来。

**Comment by alien-kai** [comment]
运行命令格式 能给我看一下吗

**Comment by alien-kai** [comment]
还有-h 是怎么用的

**Comment by foww-0001** [comment]
直接运行python3 easyai/train_task.py -h
会打印需要填入的内容。

**Comment by foww-0001** [comment]
```
Usage: train_task.py [options]

This program train model

Options:
  -h, --help            show this help message and exit
  -t TASK_NAME, --task=TASK_NAME
                        task name
  -i PATH, --trainPath=PATH
                        path to train.txt file
  -v PATH, --valPath=PATH
                        path to val.txt file
  -m PATH, --model=PATH
                        cfg file path or model name
  -p PATH, --pretrainModel=PATH
                        path to pretrain weights file
  -c PATH, --config=PATH
                        config path
```

**Comment by foww-0001** [comment]
python3  easyai/train_task.py -t ClassNet -i ${dataset_train_path} -v ${dataset_val_path} -m classnet

**Comment by foww-0001** [comment]
后两个参数可以缺少没关系。

**Comment by alien-kai** [comment]
我运行python3 easyai/train_task.py -h 就出现上面的报错

**Comment by alien-kai** [comment]
我运行完的结果是在哪里

**Comment by foww-0001** [comment]
在easyai下面按ctrl+H后，隐藏目录.easy_log/snapshot下面,
有三个pt文件，分别是：最后一次迭代的结果，最好的迭代结果和优化参数。

**Comment by alien-kai** [comment]
那我该怎么知道这个模型的各种测量指标呢

**Comment by foww-0001** [comment]
.easy_log/下面的cls_evalution.txt有训练得到的结果，top1的。

**Comment by foww-0001** [comment]
> .easy_log/下面的cls_evalution.txt有训练得到的结果，top1的。

还有我忘了咱们只有四类没有top5的结果，那就只能用top1了

**Comment by foww-0001** [comment]
如果需要top5的话，在.easy_log/config/classify_config.py中修改：
```
"evaluation": {
    "top_k": [
        1, 5
    ],
    "type": "ClassifyAccuracy"
},
```

**Comment by foww-0001** [comment]
拉取最新代码，使用onnx模型转换：
```
python3 easyai/tools/model_tool/model_to_onnx.py -t classify -m classnet -p .easy_log/snapshot/cls_best.pt -c .easy_log/config/classify_config.json
```

**Comment by alien-kai** [comment]
我是在哪里改选用的model？

**Comment by foww-0001** [comment]
-m 上面去改选

**Comment by alien-kai** [comment]
-m resnet18 为什么报错

**Comment by foww-0001** [comment]
这个是backbone，不是model，要去model_name中去挑选

**Comment by alien-kai** [comment]
model_name在哪

**Comment by foww-0001** [comment]
在easyai/name_manager/model_name.py里面
比如VggNetCls，ResNetCls

**Comment by alien-kai** [comment]
-m ResNetCls 没有报错 但也没有反应。

**Comment by foww-0001** [comment]
python3 easyai/tools/model_tool/model_block_print.py -m cfg文件

**Comment by alien-kai** [comment]
![image](https://user-images.githubusercontent.com/77905715/170022409-e586a159-106f-4d7c-abfb-bb41c75bf7b6.png)

**Comment by foww-0001** [comment]
问题是否解决，解决可以先关掉。
