### ISSUE TITLE
denet.sh运行问题

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#17]

**Comment by Shanshan7** [comment]
报错贴上来。

**Comment by alien-kai** [comment]
.easy_log目录怎么进入？

**Comment by alien-kai** [comment]
<img width="526" alt="Screen Shot 2022-05-25 at 15 50 10" src="https://user-images.githubusercontent.com/77905715/170209859-5ff53560-456f-4add-b3f6-a089956c1809.png">

**Comment by foww-0001** [comment]
问题已经解决，可以关掉。
