### ISSUE TITLE
onnx模块编译问题

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#18]
<img width="1273" alt="Screen Shot 2022-06-13 at 14 20 04" src="https://user-images.githubusercontent.com/77905715/173291744-79a67c8a-1271-41a3-904a-7ae112c1aada.png">

**Comment by Shanshan7** [comment]
头文件引入了没有呢，我看了提到分支上的代码中缺少头文件。

**Comment by alien-kai** [comment]
我之后加进去了

**Comment by Shanshan7** [comment]
新的代码可以提到分支上来我看看。

**Comment by alien-kai** [comment]
我的本地h头文件 git无法上传 不知道为什么

**Comment by Shanshan7** [comment]
你可以删除本地的分支之后，重新切换到你的分支，再把头文件贴上去上传。

**Comment by alien-kai** [comment]
我上传好了

**Comment by alien-kai** [comment]
我这边解决不了 目前不知道是cmake的问题还是头文件的问题

**Comment by alien-kai** [comment]
解决方法：include_directories(${PROJECT_SOURCE_DIR}/onnx)

file(GLOB ONNXSRCS
    "${PROJECT_SOURCE_DIR}/onnx/*.cpp"
)

target_sources(test_traffic_lights_classifier
        PRIVATE
        "${PROJECT_SOURCE_DIR}/test_traffic_lights_classifier.cpp"
        ${SRCS}
        ${ONNXSRCS}
        )
