### ISSUE TITLE
红绿灯CNN算法的实验

### ISSUE THREAD

**Issue by Shanshan7** [Shanshan7/easy_ml_inference#5]

**Comment by Shanshan7** [comment]
分类的训练框架可以使用我们的训练框架easyai框架。
https://github.com/MiniBullLab/easy_ai.git

**Comment by alien-kai** [comment]
能写一下这个框架的具体操作步骤吗

**Comment by alien-kai** [comment]
数据集txt格式是 idx path annotation?
path是 ../00x.. ?

**Comment by foww-0001** [comment]
### 分类
- 目录文件结构：
```
dataset
├── ImageSets
│   ├── train.txt
│   ├── val.txt
└── JPEGImages(*.jpg,*.png,*.bmp,*.jpeg)
```
- 标注格式：
在train.txt, val.txt中
```dotnetcli
image_path(JPEGImages为root路径下的相对路径) annotation
```

**Comment by foww-0001** [comment]
> 数据集txt格式是 idx path annotation? path是 ../00x.. ?
path就是 00xx/*.jpg

**Comment by alien-kai** [comment]
git clone使用了加速器还是很慢

**Comment by alien-kai** [comment]
在跑train_task.py的时候报错

**Comment by foww-0001** [comment]
链接：https://pan.baidu.com/s/1XB-8V037efFPQcdP3shdGA 
提取码：tpc5
