### ISSUE TITLE
关于红绿灯算法接口的问题

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#6]
目前来说 我是读入一张图片 还是 一段视屏？ 要是读入图片的话 没有办法判断off是否是闪烁灯

**Comment by foww-0001** [comment]
算法的接口是图片，在main函数中读入一段视频，然后把kcf的结果保存为一个txt文件，用于main函数的读取图片的roi区域进行测试。

**Comment by foww-0001** [comment]
然后问题的title给的长一点

**Comment by alien-kai** [comment]
好的 那我这里接口先只要做图片就行了吗

**Comment by foww-0001** [comment]
接口只要做图片就行，最终的也是视频帧截取成图片喂到算法中。
