### ISSUE TITLE
git push问题

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#7]
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 4781
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

这个怎么解决？

**Comment by foww-0001** [comment]
具体操作命令是什么导致报错呢

**Comment by alien-kai** [comment]
git push dev_zzk:develop

**Comment by foww-0001** [comment]
给我一个远程工具，我上去看一下

**Comment by alien-kai** [comment]
向日葵吗

**Comment by foww-0001** [comment]
可以的

**Comment by alien-kai** [comment]
220724222
08nhlx

**Comment by foww-0001** [comment]
申请自己的token：
https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
https://blog.csdn.net/chengwenyang/article/details/120060010
