### ISSUE TITLE
红绿灯json参数文件

### ISSUE THREAD

**Issue by alien-kai** [Shanshan7/easy_ml_inference#9]

**Comment by foww-0001** [comment]
json的头文件和cpp文件在3rd_party的json里面。
使用以下方式来读取:
```
#include <json/json.h>
#include <fstream> 
std::string camera_calibration_file = "my_path.json";

Json::Reader reader;
Json::Value root;
 
std::ifstream camera_calibration_in(camera_calibration_file, std::ios::binary);

if (!camera_calibration_in.is_open())
{
    std::cout << "Error opening file\n";
    return;
}

if (reader.parse(camera_calibration_in, root))
{
      double time_interval = root["paramater"]["time_interval"].asDouble();
      int camera_position_pixel = root["paramater"]["camera_position_pixel"].asInt();
  }
  camera_calibration_in.close();
```
使用以下方式来写入:
```
#include <json/json.h>
#include <fstream> 
std::string save_path = "my_path.json"
//根节点  
Json::StyledWriter sw;
Json::Value root;

root["target_type"] = Json::Value(1);

std::ofstream os;
os.open(save_path.str(), std::ios::out | std::ios::app);
if (!os.is_open())
    std::cout << "[error: can not find or create the file which named \" ***.json\"]." << std::endl;
os << sw.write(root);
os.close();
```

**Comment by alien-kai** [comment]
Undefined symbol: Json::Value::Value(Json::ValueType)

我这里库可以用 但还是报错

**Comment by foww-0001** [comment]
看一下头文件的路径引用对了吗

**Comment by alien-kai** [comment]
关键词都可以识别 但就是跑不了

<img width="1084" alt="Screen Shot 2022-04-25 at 15 16 52" src="https://user-images.githubusercontent.com/77905715/165039131-a83cba1a-8d2f-4166-a629-a759f6e4c485.png">

**Comment by foww-0001** [comment]
是编译报错还是运行报错？

**Comment by alien-kai** [comment]
build failed

**Comment by foww-0001** [comment]
你再自己试试，我这边晚点远程帮你看看

**Comment by alien-kai** [comment]
好的

**Comment by alien-kai** [comment]
ld: library not found for -lglog
cmake遇到bug

**Comment by Shanshan7** [comment]
> ld: library not found for -lglog cmake遇到bug

这个是输入log的库，不需要的库去掉。

**Comment by alien-kai** [comment]
<img width="920" alt="Screen Shot 2022-04-28 at 16 15 12" src="https://user-images.githubusercontent.com/77905715/165708706-fb406ab9-8e13-4e93-bfae-1ffb912a9d1d.png">
这个bug怎么解决

**Comment by Shanshan7** [comment]
给我个远程看一下，之前那个向日葵还能用吗

**Comment by alien-kai** [comment]
你稍等一下

**Comment by Shanshan7** [comment]
opencv库已经上传到develop分支

**Comment by alien-kai** [comment]
<img width="479" alt="Screen Shot 2022-04-29 at 14 50 48" src="https://user-images.githubusercontent.com/77905715/165897205-42516cd2-856b-40a4-884e-0ff2b1f54c72.png">
遇到了新bug

**Comment by Shanshan7** [comment]
> <img alt="Screen Shot 2022-04-29 at 14 50 48" width="479" src="https://user-images.githubusercontent.com/77905715/165897205-42516cd2-856b-40a4-884e-0ff2b1f54c72.png">
> 
> 遇到了新bug

在哪个环境下编译的呢

**Comment by alien-kai** [comment]
mac

**Comment by alien-kai** [comment]
#1.cmake verson
cmake_minimum_required(VERSION 3.5.0)

#2.project name
project(yolov5rt)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_BUILD_TYPE Release)

#add_definitions(-DFEATURE_MATCH_EN)

#include MOT headers
include_directories(${PROJECT_SOURCE_DIR}/)
include_directories(${PROJECT_SOURCE_DIR}/common)
include_directories(${PROJECT_SOURCE_DIR}/json/include)
include_directories(${PROJECT_SOURCE_DIR}/opencv/include)

#collect image acquisition files
find_package(OpenCV REQUIRED)

file(GLOB SRCS
    "${PROJECT_SOURCE_DIR}/*.cpp"
	)

aux_source_directory(${PROJECT_SOURCE_DIR}/json/src SRC_DIR)
add_executable(test_traffic_lights_classifier "")

target_sources(test_traffic_lights_classifier
        PRIVATE
        "${PROJECT_SOURCE_DIR}/test_traffic_lights_classifier.cpp"
        ${SRCS}
        )

# link libraries
target_link_libraries(test_traffic_lights_classifier ${OpenCV_LIBS})

**Comment by alien-kai** [comment]
这样写对吗

**Comment by Shanshan7** [comment]
opencv的库不能通过搜素加进去，要这样加进去：
```
include_directories(${PROJECT_SOURCE_DIR}/../3rd_party/opencv/include)

#collect image acquisition files
# find_package(OpenCV REQUIRED)
link_directories(${PROJECT_SOURCE_DIR}/../3rd_party/opencv/lib)

file(GLOB SRCS
    "${PROJECT_SOURCE_DIR}/*.cpp"
	)

add_executable(test_traffic_lights_classifier "")

target_sources(test_traffic_lights_classifier
        PRIVATE
        "${PROJECT_SOURCE_DIR}/test_traffic_lights_classifier.cpp"
        ${SRCS}
        )

# link libraries
target_link_libraries(test_traffic_lights_classifier
                      opencv_core
                      opencv_imgcodecs
                      opencv_imgproc
                      opencv_videoio)
```

**Comment by Shanshan7** [comment]
> link_directories(${PROJECT_SOURCE_DIR}/../3rd_party/opencv/lib)
链接到文件夹中的库

**Comment by alien-kai** [comment]
加了 还是报错

**Comment by alien-kai** [comment]
我换linux试一下
